# gosec configuration file for Todo API
exclude:
  - "G101"
  - "G103"
  - "G104"

excluded-dirs:
  - api/gen
  - vendor

rules:
  G101:
    ignores:
      - "/todo.v1.*"
      - "/common.v1.*"

global:
  nosec: false
  show-ignored: false
  tests: true
  autogen: true