# gosec configuration file
exclude:
  # Ignore gRPC generated code warnings
  - "G101"
  # Ignore unsafe usage in protobuf generated code
  - "G103"

# Exclude specific directories
excluded-dirs:
  - api/gen

# Rule overrides
rules:
  # Allow specific patterns for gRPC method names
  G101:
    ignores:
      - "/todo.v1.*"

# Global settings
global:
  # Skip tests
  nosec: false
  # Show all issues including nosec
  show-ignored: false